# Generated by Django 3.0.2 on 2020-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_price',
            field=models.IntegerField(default=1),
        ),
    ]
